### ISSUE TITLE
Build does show a blank screen on OP-Z

### ISSUE THREAD

**Issue by mazApp** [teenageengineering/videolab#1]
Hi,
I did not find another way to ask, so I try it this way.
I downloaded videolab and follwed the wiki to build a kind of "hello world" as starting point.
After compiling it starts on the mac, but not on the iPhone in the OP-Z App. It is shown there, but only a blank screen.
I tried to export as iOS afterwards, but the generated Xcode project faild (i have an developer account and normally it works).
If the iOS export is needed, it would be nice to get a hint. Than I can fix the Signature thing. If not, it would be helpfull, just to have a complete list of parameter or things, I have to do, when build the project.
Everything looks very prommising, bbut can not get the last 2% ;-)
Thanks, Stefan

**Comment by mazApp** [comment]
HI,
got closer ;-) I know now, that I have to use Asset Labels and use Assets/Build Videopaks.
But still can not see anything in the OP-Z App.
Are there special conventions for scene names etc?
Build a Patch, placed a cube. Can see it in mac Preview. Used a Patch witch Sequencer Input, Accumulator and Animator Out. But nothing happend.
Would like to do some stuff, but stopp for know until some more Infos / Tutorials are out.
Bye, Stefan

**Comment by heathcarlisle** [comment]
@mazApp 

Hello mazApp - Which version of Unity are you running? I see that 5.6.6 is the last 5x version available (8 May 2018). I'd be happy to take a look - I bought my OP-Z with Unity in mind! Can you share your project repo? cheers, -heath

**Comment by mazApp** [comment]
Hi Heath,

about say: Version 2018.2.13f1 Personal
I took the actual Version for macOS from Unity web site.

I just saw on the web site from unity that there are also 5.x branches. So I will delete the 2018 version and get the 5.6.6.

Just a few minute ago, I deleted all attempts to start fresh.

After installing 5.6.6 I will try another test and if the black screen still exist, I will share the project.

Thanks for answering,

Stefan

**Comment by heathcarlisle** [comment]
Yep, the docs call for Unity 5.x:
"
Compatibilty
Currently you need to use Unity 5.x to develop content for OP-Z. Multiple versions of Unity can co-exist on your system - on mac you need to rename any existing "Unity" application folders before installing an additional version. Grab the latest version under Unity 5.x...
"

**Comment by mazApp** [comment]
I did but with now I got an error message, that ios is not supported:

"Building a player for 'iPhone' (9) target is not supported in this Unity build.“

And the created videopak folder hat nothing in the iOS folder, only in the OSX Folder. 
Searching the web for information. Tried to install the iOS package from build settings, but nothing’s there.
Maybe it is because it is only a personal version.

I am tied of guessing and trying. :-(

But anyway, thanks a lot for the hint with the version…

**Comment by mazApp** [comment]
THANKS !

I managed to install the iOS support via Build settings and BOOM.

First videopak running on the OP-Z.
It is only a static unfancy sphere, but now the fun can start ;-)
5.6.6 was the solution. rtfm

Cheers, Stefan

**Comment by martiantek** [comment]
Hi there peeps,

I've also spent time over the last few days trying to get something viewable in the OP-Z ios app.

Bumbled my way from noob to beginner & basically got to where you guys are now

I too was using the latest build on Unity 2018 (wap wap bow)

Still gave me a chance to learn the UI & got a few apps built with midi inputs which was satisfying

My friend has a copy of Unity3D Pro 5.6.2 so I’m gonna try compiling the videopak on that & I’ll get back to y’all

P.S. I don’t get my OP-Z for another 3 weeks either

Stan

**Comment by Floflo35** [comment]
Hello,

Did anyone manage to export a videopak that does not show as a black screen once you open it in the app? It would be very helpful to quickly explain your process, because I can't even make the most basic scene work currently.

Thanks a lot! I'm loving the OP-Z so far but I'm really looking forward to mess around with Unity. 😄

**Comment by mazApp** [comment]
Yes, main things to do are:
- using Unity 5.6.6 (mot 2018)
- Installing iOS Support for Unity
- Give the Scene a Asset Label (this will the name of the Pack)
- Export via Asset/Build Videopaks
- and of course import videolab 1.0 as packet

Almost everything is in the Wiki, but if you are not used to Unity (as I am), i take some time from black screen to fun stuff ;-)
