### ISSUE TITLE
videolab patch view doesn't support latest Unity 2018

### ISSUE THREAD

**Issue by SuperMegaPlantet** [teenageengineering/videolab#11]
Patch nodes can't be created in latest Unity 2018.
And example patches can't be shown properly.
Hoping that videolab would be compatible with the latest Unity soon.

**Comment by zuggamasta** [comment]
Hello @SuperMegaPlantet,
I had similar issues starting out. To build fully working videopak files you  currently need to use Unity 5.6.x (with iOS build support) and the official public release of videolab which can be found here: https://github.com/teenageengineering/videolab/releases/tag/v1.0



Source:
https://github.com/teenageengineering/videolab/wiki/Exporting-for-OP%E2%80%90Z

**Comment by SuperMegaPlantet** [comment]
Hello @zuggamasta 
Thank you for your reply.
iOS Videopak can be built successfully in Unity 5.6.x, but I found some material shall be different after building, and I lose one asset.
I'll take some time to figure it out.
