### ISSUE TITLE
Exported Videopaks in the OP-Z app

### ISSUE THREAD

**Issue by cemillerena** [teenageengineering/videolab#13]
I've noticed all of my videopaks are much darker in my iOS devices than when played in the Unity player. Is this just me? Especially 3D scenes/videopaks. 

Is there a way to keep the colours true to the original scene?

Thanks

**Comment by harrison-drift** [comment]
If I had to guess I'd say this is due to the colourspace you have set up in your unity project vs. the space set up in the Videolab app (which itself is a Unity app). Could be wrong, just my 2¢

**Comment by finnTE** [comment]
Number of things can influence this:
- max 1 point light on iOS
- ambient light, skybox material and fog needs to be patched with SystemPropertyOut node
- color space gamma
