### ISSUE TITLE
Drag Event Input with Touch Controls/Mouse control?

### ISSUE THREAD

**Issue by cemillerena** [teenageengineering/videolab#15]
Hooked up my scene to have faders that track my knobs. 

I have set up the Drag Event Input to a Knob Out and I thought this was also carried to iOS touch control but I was wrong. When I use the Mouse Button Input I don't get the same results. What's the correct way to set up a drag event input with touch controls? 

Thanks!

**Comment by finnTE** [comment]
https://github.com/teenageengineering/videolab/wiki/Screen-UI
