### ISSUE TITLE
What Videolab version to use?

### ISSUE THREAD

**Issue by cemillerena** [teenageengineering/videolab#18]
So, now that the app has been updated, which Videolab version are we supposed to use?

I've been trying to use the official release with Unity 2018.2.x and although many things work, when exporting, for example Degrade and Mirror, can't be controlled through Knobs. You can patch them and try it out while in Unity, but when you upload it to the app and try to open it, the app shuts down. This used to work flawlessly in the other Unity version. 

So, maybe we should start using one of the other Videolab versions?

**Comment by iorama** [comment]
Indeed. I will make an official 1.1 release tomorrow.

**Comment by finnTE** [comment]
Indeed. I will make an official 1.1 release tomorrow.
