### ISSUE TITLE
MIDI channel mapping incorrect

### ISSUE THREAD

**Issue by Dathond** [teenageengineering/videolab#23]
Hi, there are a couple of errors in the midi channels:

1) channel 1 actually maps to 2
2) channel 8 actually maps to 6

Tested using unity 18.2 with VL-1.1. Attached simple unity scene shows the incorrect mapping.

[test_18.2.zip](https://github.com/teenageengineering/videolab/files/3000543/test_18.2.zip)

**Comment by cemillerena** [comment]
That's weird. I'm pretty sure mine is working as intended. Did you manage to fix it? I might have a look later this week to your unity scene.

**Comment by Dathond** [comment]
yeah still have the issue. attached file was made just to demonstrate the issue, just 8 cubes each triggering transform on channel 1-8. It doesn't work correctly on channel 1 and 8. Do let me know if I'm doing something wrong here :)

**Comment by finnTE** [comment]
https://www.teenageengineering.com/guides/op-z/midi#introduction

**Comment by Dathond** [comment]
sorted, yes error is on my side. I must have changed the outgoing channel without realising it at some point. Thanks fore the pointer!
