### ISSUE TITLE
Visual Compiler Error on macOS

### ISSUE THREAD

**Issue by d0minikh** [teenageengineering/videolab#30]
Hi all,

i'm trying to get the videolab to work in Unity on mac.
i'm doing every step that is described in the wiki, but everytime i get the same error.
i'm on macOS 10.15.1 and unity version 2019.2.13f1.
Visual Studio 8.3.10.2 ist installed.
I dont get any extras with the right klick in the hirachy tab.

Can someone help me please? What i'm missing here?

chers,
Dominik

Here is the Console output.

Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)

Copyright (C) Microsoft Corporation. All rights reserved.

error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/being' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/assigned' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/%' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/Silence' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/warning' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/about' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/serialized' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/fields' could not be found.
error CS2001: Source file '/Users/dominik/Documents/Unity/dfgdfgf/not' could not be found.

**Comment by Itay-benshu** [comment]
Hey mate. I had the same problem and did two things that eventually resolved the issue, maybe it will help you.

1) Changed the project name to include no spaces, before it was "OPZ Beats" and I created a new one named "OPZBeats"
2) Cloned the repo, and copied all content under the repo's "Assets" into a subfolder in the project called "Lab", as in the files are not directly under the project.

Hope that helps and good luck!

**Comment by d0minikh** [comment]
Hey, 

thanks a lot! Your second point did the trick, now it looks like it should.
But unfortunately i have another problem now.

When i'm opening the midijack windows nothing appears, instead it starts spamming the log file with tow different error massages.
A Midi Keyboard ist connected. Any further help? :)

EntryPointNotFoundException: MidiJackDequeueIncomingData
MidiJack.MidiDriver.Update () (at Assets/Lab/MidiJack/MidiDriver.cs:118)
MidiJack.MidiDriver.UpdateIfNeeded () (at Assets/Lab/MidiJack/MidiDriver.cs:108)
MidiJack.MidiDriver.get_TotalMessageCount () (at Assets/Lab/MidiJack/MidiDriver.cs:64)
MidiJack.MidiJackWindow.Update () (at Assets/Lab/MidiJack/Editor/MidiJackWindow.cs:85)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:359)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:353)
UnityEditor.HostView.SendUpdate () (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:465)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)


EntryPointNotFoundException: MidiJackCountSources
MidiJack.MidiJackWindow.OnGUI () (at Assets/Lab/MidiJack/Editor/MidiJackWindow.cs:42)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:359)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:353)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:329)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean floatingWindow, System.Boolean isBottomTab) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:374)
UnityEditor.DockArea.OldOnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:341)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:281)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by mattlittleson** [comment]
I had the same problem, here's my solution
1. use Unity 2018.2.x (I have it working with 2018.2.21)
2. use videolab 1.1 (videolab 1.1.1 doesn't appear to work 🤷‍♀)

**Comment by coral** [comment]
yeah def doesn't work on later version of Unity

**Comment by d0minikh** [comment]
Hey guy's,

sorry for my late response. It works now perfect, the tip withe the version solved the problem.
I'm using version 2018.2.21f1 now an as far as i can tell, everything works perfect. :)

many thanks to you guy's!
wish you all a merry christmas

**Comment by sichtbeton** [comment]
but using 2018.2. lets you build stuff you can use with the 1.2 version of the ios app? does it work?
