### ISSUE TITLE
18.4. Unity does not work with 1.1.1. videolab

### ISSUE THREAD

**Issue by sichtbeton** [teenageengineering/videolab#37]
It's all very confusing, so lets see if I just made a mistake or its really this broken. I tried to get videolab to work with the latest recommended Unity version (18.4) so that I could built stuff for the IOS app version 1.2. But as others have said: it doesnt work. It throws errors in the console concerning Visual Code "not found".

So the info in the wiki is clearly wrong. 

So again: what do I need to (which exact version / build. nr) to build paks for IOS on Mac (mojave) with unity and videolab for the latest IOS app version (1.2.4 I guess)?

This is not very straightforward and no wonder that not a lot of people go down this rocky path of building something fun for their op-z. So please TE, can we get this to work without hours of trial and error?

**Comment by finnTE** [comment]
Since this works on our setups you need to be very specific about your problems. What steps did you take? What are the exact errors you get?

**Comment by sichtbeton** [comment]
thank you for getting back to me. so here we go. 

**Method 1 (18.4.19f1 plus videopackage 1.1.1. directly):**

installed unity 18.4.19f1 on a fresh macbook mojave install without anything on it. checked all the boxes in install to include ios and mac support as well as visual code. install finished. after starting, make a new project and import the 1.1.1. videolab package from github via import custom package. clicked import all. now its taking a while. after that, i cannot right click and find midi jack or any other videolab-related stuff in the hierarchy. also there is an error code in the console. somebody else on the issues forum here posted the same. so all in all: not working.

Errors:

> Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/assigned' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/%' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/Silence' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/warning' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/about' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/serialized' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/fields' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/not' could not be found.
> error CS2001: Source file '/Users/jens/Desktop/videolabzeug/test5/being' could not be found.
> 

**Method 2 (18.4.19f1 plus cloned repo as .zip)**

it does work however if I download the latest repo via .zip and open the resulting folder as if it was project. it does throw another error:

> Your project was last saved with a different version of Unity.
>    /Users/jens/Desktop/videolab-master 2
> The saved project (2018.2.15f1) does not match the launched editor (2018.4.19f1).
> This may require re-import. Please be aware that opening in an older version is unsupported.
> Note that if a build target installation is missing, this may also cause a re-import.
> If you proceed, some packages may be updated. For a list of any changes made to your Project’s packages, see the Logs/Packages-Upgrade.log file in your Project folder.
> 

after clicking continue, it takes a while, then opens.  this gives me the right-click options that are supposed to be there in the hierarchy.  but there are more errors in the console.

> Assets/Videolab/Videopak/VideopakManager.cs(81,26): warning CS0618: `UnityEngine.SceneManagement.SceneManager.UnloadScene(string)' is obsolete: `Use SceneManager.UnloadSceneAsync. This function is not safe to use during triggers and under other circumstances. See Scripting reference for more details.'
>  Editor: Metal support disabled, skipping device initialization
> Packages were changed.
> Update Mode: updateDependencies
> The following packages were added:
>   com.unity.collab-proxy@1.2.15
> Rebuilding Library because the asset database could not be found!

and everything else "seems" to work. also: I noticed that when I build a videopak with an effect from kino with a videoplayer component, it gives me a pink full screen on IOS. in unity it works. maybe thats related to the errors above or its something to do with unity. dont know, but all in all its very very trial and error, hit and miss and to be honest: very uninviting for a feature that is so heavily marketed.

so as I am a total unity newbie all of this might be user error and I apologize in advance to the devs and everybody involved if I come across as upset, but I find the workflow and the guidance on this very sparse and kind of a bad experience. because otherwise I love my op!

**Comment by finnTE** [comment]
The console output on method 2 is just benign warnings. I have no idea why the unityPackage import fails, will try it myself in 2018.4.19 when (if) I have a moment

**Comment by sichtbeton** [comment]
@finnTE thanks!

also: I got the effects to work, it was the opengles setting you talked about in the wiki. my bad, i am a unity idiot.

but the gamma on the kino-effects is off, even though there is no lights in the scene, ouput on ios is set to gamma and opengles2. I dont know what you meant by patching skybox with systemout. so the kino-effects half-work right now. they do, but look not as intended.

**Comment by juliensnz** [comment]
Exact same error here with method 1. I have no idea how to fix it and cannot understand the error neither

**Comment by georgechond94** [comment]
In order to make method 1 to work you have to downgrade to .NET 3.5. (that's at least what worked for me)

To do that: `File -> Build Settings -> Player Settings... -> (in the inspector view) Other Settings -> Configuration -> Scripting Runtime Version -> **.NET 3.5 Equivalent (Deprecated)**`
