### ISSUE TITLE
op-z mac app not showing custom videopaks

### ISSUE THREAD

**Issue by sichtbeton** [teenageengineering/videolab#38]
the op-z mac app does not show any custom videopaks when added to the package content under data > videopaks. 

it only shows the two factory paks and nothing else. it works in the ios app though.

version: 
1.2 mac app
1.2.4 ios app

unity 18.4.19
videolab 1.1.1 (installed as repo copy from today)

what am i doing wrong?

**Comment by finnTE** [comment]
added some missing info here:
https://github.com/teenageengineering/videolab/wiki/Exporting-for-OP%E2%80%90Z

**Comment by sichtbeton** [comment]
thanks for the info!

**Comment by sichtbeton** [comment]
well on mojave, this folder does not exist after installing op-z app 1.2.4. even creating it and placing videopaks in there does not get them to show up in the app. 

~/Library/Application\ Support/com.teenageengineering.te012.osx/videopaks

it does strangely exist in the Application Scripts folder (also in library) but without anything in it.

the issue remains.

**Comment by georgechond94** [comment]
@sichtbeton 
For me, the videopaks folder was in the (quite strange) path: `/Users/username/Library/Containers/com.teenageengineering.te012.osx/Data/Library/Application Support/com.teenageengineering.te012.osx/videopaks`

`find / -type d -name "*videopaks*"` to find the folder. Adding my videopaks there worked.

I am on Mojave too.

**Comment by sdhuys** [comment]
> @sichtbeton
> For me, the videopaks folder was in the (quite strange) path: `/Users/username/Library/Containers/com.teenageengineering.te012.osx/Data/Library/Application Support/com.teenageengineering.te012.osx/videopaks`
> 
> `find / -type d -name "*videopaks*"` to find the folder. Adding my videopaks there worked.
> 
> I am on Mojave too.

Same here on macOS Catalina. Thanks!

**Comment by ikriz** [comment]
The process has changed you can import videopaks through the op-z app on mac itself
