### ISSUE TITLE
1.1.x Version of the iOS app

### ISSUE THREAD

**Issue by heathcarlisle** [teenageengineering/videolab#4]
Hello - and thanks for adding Unity 2018.2.x support. Are Unity developers able to get on the beta list for the 1.1.x version of the iOS app to take advantage of this? The current app store version reports 1.0.5. Where might one submit such a request?

**Comment by kevinloustau** [comment]
+1

**Comment by finnTE** [comment]
We will release OP-Z app 1.1 very soon.
