### ISSUE TITLE
Do I have to change midi source before exporting to iOS?

### ISSUE THREAD

**Issue by latenitecali** [teenageengineering/videolab#42]
Hey all, I just started playing around with videopak today, so I might be missing something. I got the whole pipeline working with a really basic animation using a Note Input to fire on every kick drum. When I'm testing in Unity with my op-z hooked up through usb, I do as the tutorials said and create a new Midi Source, select my op-z in the inspector, then choose this Midi source for the source on the note input node. The only way I could get this animation to work when exported to my iPad (op-z hooked up through bluetooth) was to select None as the node's source. Does this make sense, and is this the intended way to do things? Seems like a hassle to have to flip those back and forth.

Maybe I'm missing something, but it seems like when my op-z is set as the midi source in the unity project, it isn't able to trigger animations when hooked up to iPad.

**Comment by georgechond94** [comment]
@jonathanhirz What happens when u select `Auto-connect` in the Midi source's inspector panel?

**Comment by latenitecali** [comment]
Honestly, I can't get any animations to work on my ipad paks anymore. Not sure what combination of things I had going a few nights ago, but it's gone, haha. I think I will just focus on running things through the unity editor for now.

**Comment by dromsynt** [comment]
You only need MidiSource / MidiDestination components if you are using videolab with a complex MIDI setup on your computer, where multiple devices are routed to different effects. When exporting and running on a different machine (eg iPhone) the MIDI devices will not be recognised.

**Comment by latenitecali** [comment]
@dromsynt thank you, taking that out fixed everything it seems. Not sure which tutorial I followed that had that as a first step. =]
