### ISSUE TITLE
Unity Errors: The name 'ZipFile' does not exist in the current context

### ISSUE THREAD

**Issue by antiero** [teenageengineering/videolab#54]
macOS, Unity 2018.4.36f1 and 2020.3.13f1 versions.

On importing videolab-1.1.3.unitypackage and setting Unity Project Api Compatibility level to .NET 4.x I'm getting the following Console errors:

`Assets/Videolab/Videopak/VideopakManager.cs(49,9): error CS0103: The name 'ZipFile' does not exist in the current context`

**Comment by kristen-movares** [comment]
Support for 2020 isn't done yet (this error does disappear if you have .Net Core selected) use 2018.4.29

**Comment by ikriz** [comment]
Support for 2020 isn't done yet (this error does disappear if you have .Net Core selected) use 2018.4.29

**Comment by antiero** [comment]
Closing as duplicate of #55
