### ISSUE TITLE
videolab support for Unity 2019, 2020, latest LTS releases?

### ISSUE THREAD

**Issue by antiero** [teenageengineering/videolab#55]
I **love** the videolab project and have just starting to make a few fun things 🙂 

But a number of Unity assets and Unity features are supported in 2019 or later, and the currently supported Unity version for videolab is 2018.4.29f1.

Are there any plans to update videolab to work with the latest [Unity LTS versions](https://unity3d.com/unity/qa/lts-releases)?

**Comment by tricky30de** [comment]
True I tried to migrate it to 2020, but this didn't work. I try to use the Midi Jack with it.

**Comment by ikriz** [comment]
Midi jack has been superseded by Minis so change is needed on the videopak side and the OP-Z app side, But i too would like it if 2020 was supported 😊

**Comment by AntonyNasce-UH** [comment]
Any update on this?

**Comment by antiero** [comment]
Tested this in 2022, seems to work - docs need updating now?
