### ISSUE TITLE
Issue when building videopak on osx 

### ISSUE THREAD

**Issue by stephenhandley** [teenageengineering/videolab#7]
I'm using videolab 1.1 beta 2 following this tutorial https://www.youtube.com/watch?v=-ucthiCRQRI and I'm running into the following issue when building a videopak in unity. 
![screen shot 2018-12-06 at 12 29 15 pm](https://user-images.githubusercontent.com/3257/49685112-6ca93d80-fa92-11e8-91b7-4e7a45a201ed.png)

**Comment by kevinloustau** [comment]
When you installed Unity, did you install the mac os platform too? Even if you are on windows you need it.

**Comment by stephenhandley** [comment]
i'm on mac and just realized for some reason the iOS build support wasn't installed. Re-installing unity 5.6.6 with iOS support fixed things
