### ISSUE TITLE
arp doesn't send MIDI notes

### ISSUE THREAD

**Issue by keijiro** [teenageengineering/videolab#8]
It seems that arp doesn't send any MIDI notes to videolab on OP-Z app.

I uploaded a minimum project that can reproduce the issue.

https://drive.google.com/drive/folders/1bmsSjU9SorenHtXuruHVTHulq75I1u_1?usp=sharing

It receives all incoming note-on events via Note Input and plays a simple animation on a sphere.

![patch](https://i.imgur.com/16UxFEil.jpg)

It reacts to any note (including arp) on Editor, but doesn't react to arp when installed to OP-Z app as a videopak.

I tested it with 1.1.17 OS and 1.1.0 beta (251) app.

**Comment by finnTE** [comment]
Looking into it.

**Comment by finnTE** [comment]
Fixed in 1.1
